# config/database.yml

default: &default
  adapter: sqlite3
  pool: 1
  timeout: 500

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: storage/production.sqlite3
